import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
  resolve: {
    tsconfigPaths: true,
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: ['./src/setup-tests.ts'],
    include: ['src/**/*.test.{ts,tsx}'],
    exclude: ['src/**/*.integration.test.{ts,tsx}'],
    coverage: {
      provider: 'istanbul',
      reporter: ['lcov', 'text'],
      reportsDirectory: '../coverage/frontend',
      all: true,
      include: [
        'src/components/i18n/language-toggle.tsx',
        'src/components/shared/form/**/*.{ts,tsx}',
        'src/components/shared/resource/**/*.{ts,tsx}',
        'src/components/theme/theme-toggle.tsx',
        'src/features/**/components/*-form.tsx',
        'src/features/auth/components/auth-shell.tsx',
        'src/features/classroom-reservation/components/classroom-reservation-row.tsx',
        'src/features/schedule/components/dnd/conflict-message.ts',
        'src/features/schedule/hooks/**/*.{ts,tsx}',
        'src/hooks/**/*.{ts,tsx}',
        'src/lib/**/*.{ts,tsx}',
      ],
      exclude: [
        'src/**/*.test.{ts,tsx}',
        'src/test/**',
        'src/app/**',
        'src/messages/**',
        'src/types/**',
        'src/**/types.ts',
        'src/**/actions.ts',
        'src/**/queries.ts',
        'src/**/*.d.ts',
        'src/components/ui/**',
        'src/components/providers/**',
        'src/components/layout/**',
        'src/components/theme/theme-provider.tsx',
        'src/components/shared/generic-bulk-uploader.tsx',
        'src/components/shared/schedule/classroom-timeline-week.tsx',
        'src/components/shared/schedule/use-schedule-export.ts',
        'src/lib/api/server.ts',
        'src/lib/api/realtime.ts',
        'src/lib/auth/session.ts',
        'src/lib/i18n/**',
        'src/proxy.ts',
        'src/setup-tests.ts',
        'src/features/**/components/*-actions.tsx',
        'src/features/**/components/*-bulk-uploader.tsx',
        'src/features/**/components/*-form-modal.tsx',
        'src/features/**/components/*dashboard*.tsx',
        'src/features/**/components/*planner*.tsx',
        'src/features/schedule/components/schedule-generator.tsx',
        'src/features/schedule/components/schedule-importer.tsx',
        'src/features/schedule/components/schedule-planner-editor.tsx',
        'src/features/schedule/components/dnd/draggable-slot.tsx',
        'src/features/schedule/components/dnd/droppable-cell.tsx',
        'src/features/schedule/services/**',
        'src/features/schedule/utils.ts',
        'src/features/schedule-time-config/components/time-config-manager.tsx',
        'src/features/notification/components/notification-bell.tsx',
        'src/features/profile/components/profile-page-client.tsx',
      ],
      thresholds: {
        statements: 80,
        branches: 80,
        functions: 80,
        lines: 80,
      },
    },
  },
});
