sonar.projectKey=TFG-horarios_tfg-horarios-joel
sonar.organization=tfg-horarios

sonar.sources=backend/src,frontend/src,shared/src
sonar.tests=backend/src,frontend/src,shared/src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx