export const ROLES = {
  ADMIN: 'admin',
  EDITOR: 'editor',
  VIEWER: 'viewer',
} as const;

export type AppRole = (typeof ROLES)[keyof typeof ROLES];

export const PERMISSIONS = {
  MANAGE_ORGANIZATION: [ROLES.ADMIN],
  MANAGE_MEMBER: [ROLES.ADMIN],
  CREATE_ORGANIZATION_COMPONENTS: [ROLES.ADMIN, ROLES.EDITOR],
  UPDATE_ORGANIZATION_COMPONENTS: [ROLES.ADMIN, ROLES.EDITOR],
  DELETE_ORGANIZATION_COMPONENTS: [ROLES.ADMIN],
  MANAGE_RESERVATION_REQUEST: [ROLES.ADMIN, ROLES.EDITOR],
} as const;

export type AppAction = keyof typeof PERMISSIONS;
