name: CI / Tests, Quality and Covergage

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test-and-sonar:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
      DATABASE_URL: "postgres://dummy_user:dummy_pass@localhost:5432/dummy_db"
      FRONTEND_URL: "http://localhost:3000"
      JWT_SECRET: "super_secret_dummy_key_for_testing_purposes"
      JWT_EXPIRES_IN_SECONDS: "86400"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Backend Tests & Coverage
        run: bun run test:coverage
        working-directory: ./backend

      - name: Run Frontend Tests & Coverage
        run: bun run test:coverage 
        working-directory: ./frontend

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.javascript.lcov.reportPaths=coverage/backend/lcov.info,coverage/frontend/lcov.info
            -Dsonar.test.inclusions=**/*.test.ts,**/*.test.tsx
            -Dsonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**
            -Dsonar.sources=frontend/src,backend/src
