name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@9cdeeb2ef752de2ef3e1e619a24b1647d9d3d311
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
