name: Test runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: [self-hosted, tfg-prod]
    steps:
      - name: Test runner
        run: |
          hostname
          whoami
          date
          docker ps